import '../models/test_question.dart';

final List<TestQuestion> mathematicsQuestions = [
  TestQuestion(
    id: 'math_1',
    question: 'What is 2 + 2?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: '2 + 2 = 4.',
  ),
  TestQuestion(
    id: 'math_2',
    question: 'What is the square root of 9?',
    options: ['1', '2', '3', '4'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'The square root of 9 is 3.',
  ),
  TestQuestion(
    id: 'math_3',
    question: 'Solve for x: 3x + 5 = 14',
    options: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: '3x + 5 = 14, so 3x = 9, therefore x = 3.',
  ),
  TestQuestion(
    id: 'math_4',
    question: 'Find the area of a rectangle with length 8 cm and width 5 cm.',
    options: ['13 cm²', '26 cm²', '40 cm²', '45 cm²'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'Area = length × width = 8 × 5 = 40 cm².',
  ),
  TestQuestion(
    id: 'math_5',
    question: 'If log₁₀ 100 = x, then x equals:',
    options: ['1', '2', '10', '100'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'log₁₀ 100 = 2 because 10² = 100.',
  ),
  TestQuestion(
    id: 'math_6',
    question: 'The derivative of x³ is:',
    options: ['x²', '3x²', '3x³', 'x⁴'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'Using the power rule: d/dx(x³) = 3x².',
  ),
  TestQuestion(
    id: 'math_7',
    question: 'Find the value of sin 30°:',
    options: ['1/2', '√3/2', '1', '√2/2'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'sin 30° = 1/2.',
  ),
  TestQuestion(
    id: 'math_8',
    question: 'Which of the following is a perfect square?',
    options: ['48', '63', '81', '98'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: '81 = 9², so it is a perfect square.',
  ),
  TestQuestion(
    id: 'math_9',
    question: 'The sum of the first 10 natural numbers is:',
    options: ['45', '50', '55', '60'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'Sum = n(n+1)/2 = 10(11)/2 = 55.',
  ),
  TestQuestion(
    id: 'math_10',
    question: 'Simplify: (2x + 3)(x - 1)',
    options: ['2x² + x - 3', '2x² - x + 3', '2x² + x + 3', '2x² - x - 3'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: '(2x + 3)(x - 1) = 2x² - 2x + 3x - 3 = 2x² + x - 3.',
  ),
  TestQuestion(
    id: 'math_11',
    question: 'The gradient of the line y = 2x + 5 is:',
    options: ['2', '5', '7', '10'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'In y = mx + c, the gradient is m = 2.',
  ),
  TestQuestion(
    id: 'math_12',
    question:
        'Find the circumference of a circle with radius 7 cm (use π = 22/7):',
    options: ['22 cm', '44 cm', '49 cm', '154 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'Circumference = 2πr = 2 × (22/7) × 7 = 44 cm.',
  ),
  TestQuestion(
    id: 'math_13',
    question: 'If 2ˣ = 8, then x equals:',
    options: ['2', '3', '4', '8'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: '2³ = 8, so x = 3.',
  ),
  TestQuestion(
    id: 'math_14',
    question: 'The quadratic formula for ax² + bx + c = 0 is:',
    options: [
      'x = (-b ± √(b² - 4ac))/2a',
      'x = (-b ± √(b² + 4ac))/2a',
      'x = (b ± √(b² - 4ac))/2a',
      'x = (-b ± √(b² - 4ac))/a',
    ],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'The quadratic formula is x = (-b ± √(b² - 4ac))/2a.',
  ),
  TestQuestion(
    id: 'math_15',
    question: 'Express 0.375 as a fraction in its simplest form:',
    options: ['3/8', '375/1000', '15/40', '6/16'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: '0.375 = 375/1000 = 3/8 in simplest form.',
  ),
  TestQuestion(
    id: 'math_16',
    question: 'The volume of a cube with side length 4 cm is:',
    options: ['12 cm³', '16 cm³', '48 cm³', '64 cm³'],
    correctAnswer: 3,
    subject: 'Mathematics',
    explanation: 'Volume = side³ = 4³ = 64 cm³.',
  ),
  TestQuestion(
    id: 'math_17',
    question: 'Find the HCF of 24 and 36:',
    options: ['6', '8', '12', '18'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'The highest common factor of 24 and 36 is 12.',
  ),
  TestQuestion(
    id: 'math_18',
    question: 'If y = 3x² + 2x - 1, find dy/dx:',
    options: ['6x + 2', '3x + 2', '6x - 1', '3x - 1'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'dy/dx = 6x + 2 using the power rule.',
  ),
  TestQuestion(
    id: 'math_19',
    question: 'The range of the function f(x) = x² is:',
    options: ['All real numbers', 'x ≥ 0', 'y ≥ 0', 'x ≤ 0'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'Since x² is always non-negative, the range is y ≥ 0.',
  ),
  TestQuestion(
    id: 'math_20',
    question: 'Evaluate: ∫(2x + 3)dx',
    options: ['x² + 3x + C', '2x² + 3x + C', 'x² + 3x', '2x + 3'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: '∫(2x + 3)dx = x² + 3x + C.',
  ),
  TestQuestion(
    id: 'math_21',
    question: 'The mean of 5, 7, 9, 11, 13 is:',
    options: ['8', '9', '10', '11'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'Mean = (5 + 7 + 9 + 11 + 13)/5 = 45/5 = 9.',
  ),
  TestQuestion(
    id: 'math_22',
    question: 'Solve: 2x - 3 > 7',
    options: ['x > 2', 'x > 5', 'x < 2', 'x < 5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: '2x - 3 > 7, so 2x > 10, therefore x > 5.',
  ),
  TestQuestion(
    id: 'math_23',
    question: 'The inverse of the function f(x) = 2x + 1 is:',
    options: [
      'f⁻¹(x) = (x - 1)/2',
      'f⁻¹(x) = (x + 1)/2',
      'f⁻¹(x) = 2x - 1',
      'f⁻¹(x) = x/2 - 1',
    ],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'If y = 2x + 1, then x = (y - 1)/2, so f⁻¹(x) = (x - 1)/2.',
  ),
  TestQuestion(
    id: 'math_24',
    question: 'The distance between points (2, 3) and (5, 7) is:',
    options: ['3', '4', '5', '7'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'Distance = √[(5-2)² + (7-3)²] = √[9 + 16] = √25 = 5.',
  ),
  TestQuestion(
    id: 'math_25',
    question: 'If cos θ = 3/5, find sin θ (assuming θ is acute):',
    options: ['3/5', '4/5', '5/3', '5/4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation:
        'Using sin²θ + cos²θ = 1: sin²θ = 1 - (3/5)² = 16/25, so sin θ = 4/5.',
  ),
  TestQuestion(
    id: 'math_26',
    question: 'The nth term of the sequence 2, 5, 8, 11, ... is:',
    options: ['2n + 1', '3n - 1', '3n + 2', '2n + 3'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation:
        'This is an arithmetic sequence with first term 2 and common difference 3, so aₙ = 2 + (n-1)3 = 3n - 1.',
  ),
  TestQuestion(
    id: 'math_27',
    question: 'The coefficient of x² in the expansion of (x + 2)³ is:',
    options: ['3', '6', '12', '8'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation:
        'Using binomial theorem: (x + 2)³ = x³ + 3x²(2) + 3x(4) + 8. Coefficient of x² is 12.',
  ),
  TestQuestion(
    id: 'math_28',
    question:
        'The equation of a line passing through (0, 2) with gradient 3 is:',
    options: ['y = 3x + 2', 'y = 2x + 3', 'y = 3x - 2', 'y = 2x - 3'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'Using y = mx + c with m = 3 and c = 2: y = 3x + 2.',
  ),
  TestQuestion(
    id: 'math_29',
    question: 'The probability of getting a head when flipping a fair coin is:',
    options: ['0', '1/4', '1/2', '1'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation:
        'There are 2 equally likely outcomes (head or tail), so P(head) = 1/2.',
  ),
  TestQuestion(
    id: 'math_30',
    question: 'Factorize: x² - 9',
    options: [
      '(x - 3)(x - 3)',
      '(x + 3)(x + 3)',
      '(x - 3)(x + 3)',
      '(x - 9)(x + 1)',
    ],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation:
        'x² - 9 = x² - 3² = (x - 3)(x + 3) using difference of squares.',
  ),
  TestQuestion(
    id: 'math_31',
    question:
        'The sum to infinity of the geometric series 1 + 1/2 + 1/4 + 1/8 + ... is:',
    options: ['1', '1.5', '2', '∞'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'S∞ = a/(1-r) = 1/(1-1/2) = 1/(1/2) = 2.',
  ),
  TestQuestion(
    id: 'math_32',
    question: 'The value of tan 45° is:',
    options: ['0', '1/2', '1', '√3'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: 'tan 45° = 1.',
  ),
  TestQuestion(
    id: 'math_33',
    question: 'If matrix A = [2 3; 1 4], find the determinant of A:',
    options: ['5', '8', '10', '11'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation: 'det(A) = (2)(4) - (3)(1) = 8 - 3 = 5.',
  ),
  TestQuestion(
    id: 'math_34',
    question: 'The turning point of the parabola y = x² - 4x + 3 is:',
    options: ['(2, -1)', '(2, 1)', '(-2, -1)', '(-2, 1)'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation:
        'Using x = -b/2a = 4/2 = 2, and y = 4 - 8 + 3 = -1. Turning point is (2, -1).',
  ),
  TestQuestion(
    id: 'math_35',
    question: 'The standard deviation of the data set 2, 4, 6, 8, 10 is:',
    options: ['√8', '2√2', '4', '8'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'Mean = 6, variance = 8, so standard deviation = √8 = 2√2.',
  ),
  TestQuestion(
    id: 'math_36',
    question: 'Solve the simultaneous equations: x + y = 7, x - y = 1',
    options: ['x = 3, y = 4', 'x = 4, y = 3', 'x = 5, y = 2', 'x = 2, y = 5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'Adding equations: 2x = 8, so x = 4. Substituting: y = 3.',
  ),
  TestQuestion(
    id: 'math_37',
    question: 'The angle between vectors a = (3, 4) and b = (4, 3) is:',
    options: ['0°', '30°', '45°', '90°'],
    correctAnswer: 0,
    subject: 'Mathematics',
    explanation:
        'cos θ = (a·b)/(|a||b|) = 24/(5×5) = 24/25. Since both vectors have same magnitude and large dot product, θ ≈ 0°.',
  ),
  TestQuestion(
    id: 'math_38',
    question: 'The modulus of the complex number 3 + 4i is:',
    options: ['3', '4', '5', '7'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation: '|3 + 4i| = √(3² + 4²) = √(9 + 16) = √25 = 5.',
  ),
  TestQuestion(
    id: 'math_39',
    question: 'The limit of (x² - 4)/(x - 2) as x approaches 2 is:',
    options: ['0', '2', '4', 'undefined'],
    correctAnswer: 2,
    subject: 'Mathematics',
    explanation:
        '(x² - 4)/(x - 2) = (x - 2)(x + 2)/(x - 2) = x + 2. As x → 2, limit = 4.',
  ),
  TestQuestion(
    id: 'math_40',
    question: 'The area under the curve y = x from x = 0 to x = 2 is:',
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    explanation: 'Area = ∫₀² x dx = [x²/2]₀² = 4/2 - 0 = 2.',
  ),
];
